'use client'

import { motion } from 'framer-motion'
import { TrendingUp, Shield, DollarSign, BarChart3, FileText, Zap } from 'lucide-react'

const modules = [
  {
    icon: TrendingUp,
    name: 'MAX Flow',
    description: 'Real-time cash flow intelligence with multi-scenario forecasting and AI-powered anomaly detection.',
    color: '#10B981',
  },
  {
    icon: Shield,
    name: 'MAX Risk',
    description: 'Continuous risk monitoring across FX, liquidity, customer concentration, and operational dimensions.',
    color: '#3B82F6',
  },
  {
    icon: DollarSign,
    name: 'MAX Profit',
    description: 'Customer-level profitability mapping with margin analysis and payment behavior intelligence.',
    color: '#10B981',
  },
  {
    icon: BarChart3,
    name: 'MAX Forecast',
    description: 'AI-driven financial modeling with confidence intervals and scenario planning capabilities.',
    color: '#3B82F6',
  },
  {
    icon: FileText,
    name: 'MAX Board',
    description: 'One-click boardroom reports with executive narratives generated by AI, ready in seconds.',
    color: '#10B981',
  },
  {
    icon: Zap,
    name: 'MAX Signals',
    description: 'Proactive AI alerts and strategic recommendations delivered before issues become problems.',
    color: '#3B82F6',
  },
]

export default function Modules() {
  return (
    <section className="py-24 px-8">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-4xl font-bold text-white mb-4">Core Intelligence Modules</h2>
          <p className="text-[#A1A1AA] text-lg max-w-2xl mx-auto">
            Six specialized AI engines, unified in one executive platform.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {modules.map((mod, i) => (
            <motion.div
              key={mod.name}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: i * 0.07 }}
              viewport={{ once: true }}
              className="group rounded-2xl p-6 cursor-pointer transition-all duration-300 hover:-translate-y-1"
              style={{
                background: '#111111',
                border: '1px solid rgba(255,255,255,0.06)',
              }}
            >
              <div
                className="w-10 h-10 rounded-xl flex items-center justify-center mb-4 transition-all"
                style={{ background: `${mod.color}15` }}
              >
                <mod.icon className="w-5 h-5" style={{ color: mod.color }} />
              </div>
              <h3 className="text-base font-semibold text-white mb-2">{mod.name}</h3>
              <p className="text-sm text-[#A1A1AA] leading-relaxed">{mod.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}
